export const state = {
  connected: false,
  apiOnline: false,
  apiError: "",
  walletConfig: null,
  selectedWalletId: null,
  walletProvider: null,
  account: null,
  side: "YES",
  price: 47,
  sport: "football",
  tickets: [],
  portfolio: null,
  pendingTicket: null,
  balance: null,
  seenPositionCount: 0,
};
